### ISSUE TITLE
decouple training and language analysis

### ISSUE THREAD

**Issue by mbaroni** [facebookresearch/EGG#150]
### Is your proposal related to a problem?

Right now, language analysis is implemented with callback functions that operate as part of the training process. It would be cleaner and more efficient to decouple it, performing language analysis on trained agents.

### Describe the solution you'd like to have implemented

After training, it's possible to save Sender and Receiver and query them with new data for language analysis. The language analysis functions generically operate on data structures such as message and sender_input, independently of their source.

### Additional context

Solving this would probably also solve issue #148 (test set): merge?

**Comment by robertodessi** [comment]
merging with #148
