### ISSUE TITLE
Standard text format for Interaction class contents

### ISSUE THREAD

**Issue by mbaroni** [facebookresearch/EGG#155]
### Is your proposal related to a problem?

Right now, the useful logging information stored in the Interaction class is only available as a Python object. It would be good to have a standard text format for information exchange.

### Describe the solution you'd like to have implemented

Provide function printing/reading Interaction information from text file.

**Comment by mbaroni** [comment]
I am not convinced that we need anything more than what we already have.

**Comment by robertodessi** [comment]
I agree on this, I think we have enough to store and analyze interactions for now
