### ISSUE TITLE
Progress bar in command-line interface

### ISSUE THREAD

**Issue by mbaroni** [facebookresearch/EGG#157]
Add small progress bar that monitors train progress when using command line interface-based training in EGG.

**Comment by mbaroni** [comment]
Won't this make things worse for non-interactive training?

**Comment by robertodessi** [comment]
It could be disabled (even by default) for cluster-based runs and that should leave things as they are now

**Comment by robertodessi** [comment]
Added in 24c61adae6b3959e184d30a592d4001d7f89ddfd
