### ISSUE TITLE
Native edit distance

### ISSUE THREAD

**Issue by mbaroni** [facebookresearch/EGG#160]
### Is your proposal related to a problem?

Right now, computation of edit distance relies on editdistance pkg: we would like to get rid of this dependency.

### Describe the solution you'd like to have implemented

Implement our own edit distance function.

### Additional context

Remember this is a textbook example of a problem to be solved with dynamic programming.

**Comment by robertodessi** [comment]
I agree about the textbook problem but I think we should check for the performance of a proposed implementation. If it is computationally expensive it might be a bottleneck when computing topsim on a large {train|valid|test} set. Thus, I would drop the dependency (https://pypi.org/project/editdistance/) only if a proposed solution has "comparable" performance

**Comment by eugene-kharitonov** [comment]
I am actually not sure if it is worth the effort at all?..

**Comment by mbaroni** [comment]
Changed the tag to low-priority

**Comment by robertodessi** [comment]
Closing this as it's probably not worth the effort
