### ISSUE TITLE
warning in tests

### ISSUE THREAD

**Issue by mbaroni** [facebookresearch/EGG#161]
## Expected Behavior
$ pytest 
...
all tests passed, no warning

## Current Behavior
$pytest
...
/private/home/mbaroni/anaconda3/envs/the_veritable_egg/lib/python3.7/site-packages/torchvision/io/video.py:2
  /private/home/mbaroni/anaconda3/envs/the_veritable_egg/lib/python3.7/site-packages/torchvision/io/video.py:2: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
    import imp

-- Docs: https://docs.pytest.org/en/latest/warnings.html
========================================================================= 45 passed, 1 warning in 81.34s (0:01:21) =========================================================================

## Steps to Reproduce
Run
$ pytest
in EGG root directory

## Possible Implementation
avoid "import imp"?

**Comment by eugene-kharitonov** [comment]
This is coming from pytorch itself; must be already fixed in the latest version, see https://github.com/pytorch/vision/issues/1607

**Comment by robertodessi** [comment]
I guess we could upgrade the req for pytorch but not really necessary for now. I would just leave it as is for now and close this
