### ISSUE TITLE
TensorboardLogger writer is none

### ISSUE THREAD

**Issue by nicofirst1** [facebookresearch/EGG#183]
## Expected Behavior
If the user didn't install the tensorbard lib correctly, then the [get summary](https://github.com/facebookresearch/EGG/blob/88f73b9e684f8ef483c4e0d0d93fa7834fc87ce9/egg/core/util.py#L198) should raise an error. 

## Current Behavior
Right now the function prints an warning, but if you use  the [TensorboardLogger](https://github.com/facebookresearch/EGG/blob/88f73b9e684f8ef483c4e0d0d93fa7834fc87ce9/egg/core/callbacks.py#L77), at the end of the training epoch [this method](https://github.com/facebookresearch/EGG/blob/88f73b9e684f8ef483c4e0d0d93fa7834fc87ce9/egg/core/callbacks.py#L91) will trow an error since `self.writer` is None. 
For long epochs this is a waste of time 

## Possible Implementation
Either change  [this](https://github.com/facebookresearch/EGG/blob/88f73b9e684f8ef483c4e0d0d93fa7834fc87ce9/egg/core/util.py#L198) with a raise error or add an assertion of the kind 
```
assert self.writer is not None

```
in the [ TensorboardLogger init](https://github.com/facebookresearch/EGG/blob/88f73b9e684f8ef483c4e0d0d93fa7834fc87ce9/egg/core/callbacks.py#L78)

**Comment by robertodessi** [comment]
Thanks for spotting this! Feel free to open PR if you like, otherwise I'll fix it sometime next week
