### ISSUE TITLE
I am interest in the work named Cross-Domain Image Captioning with Discriminative Finetuning. Could you share the code of it?

### ISSUE THREAD

**Issue by zongzi3zz** [facebookresearch/EGG#252]
### Is your proposal related to a problem?

(Write your answer here.)

### Describe the solution you'd like to have implemented

(Describe your proposed solution here.)

### Describe alternatives you've considered

(Write your answer here.)

### Additional context

(Write your answer here.)

**Comment by robertodessi** [comment]
Answered in private communication
