### ISSUE TITLE
GUI for ECG

### ISSUE THREAD

**Issue by Abhik1998** [facebookresearch/EGG#26]
Can we get up with a GUI so that game developers can easily use this especially the Windows users?
It's just an idea and we can discuss that.

**Comment by eugene-kharitonov** [comment]
Hello! Thank you for having a look at EGG.

The "games" we currently have are not really visual and are very centered around sending sequences of symbols/strings/messages. I am not sure those would benefit from a real GUI or would be interesting to look at...

**Comment by Abhik1998** [comment]
Okay actually I wanted to join your team and contribute to ECG

**Comment by eugene-kharitonov** [comment]
Thanks! 
Let me think of some issues that would be easy to start with?

**Comment by Abhik1998** [comment]
Okay sir
