### ISSUE TITLE
Assuming message length equal to the sequence length?

### ISSUE THREAD

**Issue by backpropper** [facebookresearch/EGG#31]
Do you assume here that the input/output sequence length is the same as the message length? or bounded by it

https://github.com/facebookresearch/EGG/blob/0fddad39b934c0c5c0f5871c50346a3ea4b01629/egg/core/gs_wrappers.py#L263

**Comment by eugene-kharitonov** [comment]
Thanks giving a look! 

Yes, `max_len` only upper-bounds the number of symbols transmitted. It is possible that the <eos> is generated before `max_len` is reached, or vice-versa.

In training mode with GS it is even more tricky, as each produced "symbol" generally will have non-zero prob. of being <eos>, so we have to unroll until `max_len` is reached.

Hope that helps?

**Comment by backpropper** [comment]
Thanks for the explanation! My concern was why can it not be the case when the number of symbols be more than `max_len`?

**Comment by rahmacha** [comment]
Hi, thanks again for your interest. Just I am not sure I understand fully your question; are you asking about the message's symbols, and why we don't go further than max_len to read these symbols? Thanks!

**Comment by backpropper** [comment]
I guess eugene referred 'symbols' to the output tokens. So I used that terminology too. I'm just saying that why decoding the output tokens is dependent on the length of the message produced. They should be separate right? As in you encode the received message first and then decode for any length?

**Comment by backpropper** [comment]
Oh I see. I thought the receiver should be a seq2seq model but the output is not sequential since you predict all the features of the output at once. It makes sense now.
