### ISSUE TITLE
how about using a Straight Through estimator?

### ISSUE THREAD

**Issue by backpropper** [facebookresearch/EGG#32]
https://github.com/facebookresearch/EGG/blob/0fddad39b934c0c5c0f5871c50346a3ea4b01629/egg/core/gs_wrappers.py#L210

**Comment by eugene-kharitonov** [comment]
Hello @backpropper , thanks for a suggestion!

Yes, we should have ST GS, I think adding it would be easy and I even have it somewhere in my private branches. It was not a huge priority so far, as (I think) it was never reported to be performing considerably better than non-ST GS (eg by Havrylov & Titov or in the original GS paper).

I'll add it next week - or free feel to add it yourself!

**Comment by backpropper** [comment]
It's not really clear that non-ST GS always performs better especially in environments which involve variable length. Some recent works have used ST-GS with the other benefit of not having to unroll till max_len since its no longer continuous.

**Comment by eugene-kharitonov** [comment]
Oh, interesting, thanks! Could you share a reference?
Yes, we probably should have that, too.

**Comment by eugene-kharitonov** [comment]
Should be possible now, though the sequence is still unrolled until the end.

**Comment by eugene-kharitonov** [comment]
I don't think we'll do the rest in the nearest future, I'll close the task.
