### ISSUE TITLE
a bug in eos loss calculation?

### ISSUE THREAD

**Issue by backpropper** [facebookresearch/EGG#33]
Isn't the step loss calculated the first time the agent produces an eos token? and then everything after that is masked.
What this is doing is checking if eos was emitted in just the last timestep.

https://github.com/facebookresearch/EGG/blob/0fddad39b934c0c5c0f5871c50346a3ea4b01629/egg/core/gs_wrappers.py#L350

**Comment by eugene-kharitonov** [comment]
The logic we wanted to have is to get the expected loss as a sum of over all steps upto max_len
P(eos | step) * P(no eos happened before| step) * Loss(step)
P(no eos happened before| step=0) = 1
P(no eos happened before| step + 1) =  P(no eos happened before| step) * [1 - P(eos | step)]

Here `add_mask` is P(eos | step) * P(no eos happened before| step), `not_eosed_before` is P(no eos happened before| step).

I think this should work both when P(eos|step) is one-hot or has all its entries non-zero.

**Comment by eugene-kharitonov** [comment]
@backpropper Does it make sense?

**Comment by backpropper** [comment]
Hi, I haven't got a chance to look at it yet. Will update next week. Thanks for the clarification.

**Comment by backpropper** [comment]
So here's where I'm confused:
I'm assuming the message is one hots (ST-GS).
Given a batch: 
1. `add_mask` is supposed to capture the samples where eos is produced in the current step and masking the samples which have already produced an eos earlier.
2. `not_eosed_before` is supposed to capture all the samples where eos is produced in any of the previous steps

But instead of the above-expected behavior, what `not_eosed_before` is doing is only capturing samples which produced eos in the LAST timestep and not the whole history. Is that the intended behavior? If so how?

**Comment by backpropper** [comment]
In other words, I'm not sure if I understand this equation correctly:
`P(no eos happened before| step + 1) = P(no eos happened before| step) * [1 - P(eos | step)]`

Lets consider the deterministic setting (one-hot messages). Why are we concerned about `P(no eos happened before| s + 1)` if an eos is already emitted at `step <= s` for ANY s \in [1, s]? i.e. the loss for a sample should be masked after the first eos is emitted.

Does it make sense?

**Comment by eugene-kharitonov** [comment]
> loss for a sample should be masked after the first eos is emitted.

I think it is masked =) one eos happens, all following not_eosed_before would be zero, hence add_mask would always be zero, hence losses from each following step would be multiplied by zero before adding.

So let's consider three cases, one-hot vectors:
1/ No eos happened before and the current symbol is not eos, then:
 - P(no eos happened before| step) is 1
 - P(eos | step) is 0
 - add mask is 0
 - step loss is not changed, https://github.com/facebookresearch/EGG/blob/0fddad39b934c0c5c0f5871c50346a3ea4b01629/egg/core/gs_wrappers.py#L344

2/ No eos happened before and the current symbol is eos, then:
 - P(no eos happened before| step) is 1
 - P(eos | step) is 1
 - add mask is 1
 - step loss is incremented by the loss that Receiver gets

3/ eos happened before and the current symbol is eos, then:
 - P(no eos happened before| step) is 0
 - P(eos | step) is 1
 - add mask is 0
 - step loss is not changed
