### ISSUE TITLE
Abuse of global variables in Trainer

### ISSUE THREAD

**Issue by tomekkorbak** [facebookresearch/EGG#37]
Trainer calls a global CLI handler on initialization:
https://github.com/facebookresearch/EGG/blob/5b422b41334214ac0d43b21f43bc0988569de469/egg/core/trainers.py#L60

In the course my work with EGG I found this design choice to be very limiting: it effectively couples the `Trainer` to pre-defined common arguments that are not universally applicable (e.g. for some complex games the experiment consists of several trainer instances arguments like `num_epochs` are misleading). It would also be nice to be able to set own defaults. I would like EGG to give me the possibility of taking care of hyperparameters on my own and setting them per trainer. More concretely, could we pass configuration like checkpointing frequency, path, validation frequency as argument to `Trainer.__init__`? Is it compatible with the way you would like to see EGG being developed? If so, I'd be happy to prepare a pull request.

**Comment by eugene-kharitonov** [comment]
Hello @tomekkorbak !

Hm, indeed. So far we never had a need for several trainers somehow, and the current way of setting things up allows to reduce the number parameters to pass.

We could start with a compromise and decouple only a few of them. These three that you mentioned sound good to me!

Thanks!

**Comment by tomekkorbak** [comment]
Great, @eugene-kharitonov, I'd be happy to work on it.

In case you're curious, here's the use case I had:
https://github.com/tomekkorbak/compositional-communication-via-template-transfer/blob/1b2d4c56d50a3016d962de7bc14c78afffa3ce6e/template_transfer/train.py#L94-L127

Overall, EGG was an enormous help to get started (and get my first NeurIPS workshop paper published, you deserve a huge thank you!), but once I started experimenting with non-traditional training regimes, it lacked modularity. Relying on global states hurts modularity in general, I'm afraid. I see reasons behind this choice, though.

**Comment by eugene-kharitonov** [comment]
Awesome, congrats on the paper, well done! 💪

The trick is that we didn't know how the development of EGG (and the entire field) will go, so we decided to start as simple as possible and then re-do the parts that are too restricting for us. So your comments and suggestions are very welcome!

**Comment by robertodessi** [comment]
Closing this as it seems there has not been any recent updates. Feel free to reopen if necessary
