### ISSUE TITLE
TemperatureUpdater only defined for GumbelSoftmax

### ISSUE THREAD

**Issue by backpropper** [facebookresearch/EGG#42]
All the GS wrappers other than Gumbel Softmax are broken if temperature updating is enabled.
```
assert hasattr(agent, 'gs_layer') and hasattr(agent.gs_layer, 'temperature'), 'Agent must have a `temperature` attribute'
AssertionError: Agent must have a `temperature` attribute
```

**Comment by eugene-kharitonov** [comment]
Could you please specify the behaviour you would expect?

**Comment by backpropper** [comment]
I'm saying that it gives an error since `gs_layer` is not defined for any other wrapper other than `GumbelSoftmaxWrapper`
